# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actionsrelease

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build --if-present
    - name: Git Commit/Push Changes
      uses: actions-x/commit@v2
    - name: Create Pull Request
      # You may pin to the exact commit or the version.
      # uses: peter-evans/create-pull-request@9825ae65b1cb54b543b938503728b432a0176d29
      uses: peter-evans/create-pull-request@v3.10.0
      with:
        # GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)
        # The pull request branch name.
        branch: release
        delete-branch: false
        title: actions - PR with Main branch artifacts
        # The body of the pull request.
        body: Incoming changes from building main branch
